main: nl.dantevg.dynmapexport.DynmapExport
name: DynmapExport
version: ${version} # Filled in automatically by maven
api-version: 1.13
description: Automatically export dynmap tiles periodically
author: RedPolygon
website: dantevg.nl/mods-plugins/DynmapExport
softdepend: [dynmap]
commands:
  dynmapexport:
    description: DynmapExport command
    usage: "Usage:\n/dynmapexport now\n/dynmapexport export <world> <map> <x> <z> <zoom>\n/dynmapexport reload"
    permission: dynmapexport.*
permissions:
  dynmapexport.*:
    description: Allows running /dynmapexport command
