main: nl.dantevg.dynmapexport.DynmapExport
name: DynmapExport
version: ${version} # Filled in automatically by maven
api-version: 1.13
description: TODO
author: RedPolygon
website: dantevg.nl/mods-plugins/DynmapExport
commands:
  dynmapexport:
    description: DynmapExport command
    usage: "Usage: /dynmapexport <world> <map> <chunkX> <chunkZ> <zoom>"
    permission: dynmapexport.*
permissions:
  dynmapexport.*:
    description: Allows running /dynmapexport command
